### ISSUE TITLE
Devices not working on Smart Watch

### ISSUE THREAD

**Issue by pijulius** [hongtat/tasmota-connect#11]
Hi Hong Tat,

First of all thanks for all your work on this implementation, it works perfectly and was able to replace all my tuya setup with SmartThings so I'm already very happy :)

Now, just one small thing that I cannot realize why it may not work, tried playing around with the code through the weekend but still can't find a solution.

The problem is that when you install Smart Things on your smart watch and you add a widget for the devices and add a device like a Generic Button from Tasmota it simply doesn't do anything, I thought maybe it is because of missing capabilities in the metadata but didn't find much. Also I can confirm if I add Scenes to the watch all is working great it's only the Tasmota devices that don't do anything if clicked on smart watch.

Could you please help out with this, may it be something that this implementation missing or is it maybe a limitation from SmartThings?

Thanks in advance!
Julius

**Comment by hongtat** [comment]
Hi Julius,

The virtual button is paired with a physical remote controller for automation, it doesn't allow direct interaction (can't tap on the button) in SmartThings app. Have you tried other devices, such as generic switches, and non-Tasmota devices (Zwave, Zigbee)?

If non-Tasmota devices work on your smart watch, I believe Tasmota devices should work too, however, I don't have a smart watch, I'm unable to check.

**Comment by pijulius** [comment]
Hi Hong Tat,

Indeed, you were right, it has nothing to do with tasmota integration at all so will close this issue.

For now what I did is changed the tasmota device handlers and replaced power on with TOGGLE this way I can create a scene where if pressed it won't just turn devices on but turn them off too and so far it works, Would have been better to be able to add another command to the On , Off options like Toggle but I wasn't able to do so it seems the new Samsung Smart Things app doesn't support custom commands or at least I wasn't able to find out a way to do it.

Thanks again for the quick response and for your work on this integration, very much appreciated!

Regards,
Julius
