### ISSUE TITLE
Tasmota 8.2 - Smartthings - Turning off generic dimmer

### ISSUE THREAD

**Issue by ipnextgen** [hongtat/tasmota-connect#2]
Hi,

Thanks for all that great work of yours!

I'm having issue turning off Generic Dimmers. In the classic and new version of smartthings I can control "turn on" and "dim level" perfectly. Once I want to power off the device, the "power" icon spins and spins and finally the application display "Network connection error". The dimmer DO get turned off but the device in smartthings is still "On" and I cannot control it anymore. I cannot turn it back On or Off.

What is weird, its works perfectly in google home and tasmota device web ui??

If you need video, json's whatever, just ask.

Thanks

**Comment by hongtat** [comment]
Hello,

Can you update the code and see whether it works for you now?

**Comment by ipnextgen** [comment]
It is working!! Thanks for the fix!
