### ISSUE TITLE
No devices available in the app.

### ISSUE THREAD

**Issue by shevett** [hongtat/tasmota-connect#20]
Hi there, I have Tasmota installed on a device on my local network, and can see it from a browser just fine (it's a Wyze bulb).  Commands to the MQTT broker cause the light to go on and off.

I've installed tasmota-connect via the IDE, and added the smartapp and device handlers per the docs.  

However, when I go to the smartapp on the phone, and go to add a new device, I see no 'Installed devices', and when clicking on "New tasmota device" all I see is the following screen - no device types or options are available - so i can't specify the IP address of the tasmota device.

<img src="https://user-images.githubusercontent.com/3791161/109375549-a214ee00-788b-11eb-9f53-32a6091ef3b9.png" width="200">

I'm wondering if the device handlers did not register properly?  They're all showing published... 

<img src="https://user-images.githubusercontent.com/3791161/109375629-32533300-788c-11eb-84d7-7ca8ec598366.png" width="200">

**Comment by chrisb22** [comment]
I think this is normal behavior. Click on the text "Which device...." Then you will get the options.

**Comment by shevett** [comment]
@chrisb22 AHA.  Yes, that is correct - I had no inkling that wa sa button.  I may submit a PR to make that more apparent / update the docs.

One more question - it's looking like tasmota connect is talking directly to the device, not to MQTT - is that correct?  Tasmota is designed to use the queue service for all communication.  I assume the IP address being requested is the bulb itself?  Or is it asking for the MQTT server?

**Comment by hongtat** [comment]
@shevett - Fill in the IP address, username (optional), password (optional) of the Tasmota device

**Comment by shevett** [comment]
@hongtat the issue is the form is very difficult to understand, and I didn't know that "Which device do you want to add?" was a button to press.  It's working now.
