### ISSUE TITLE
[ST Offline] 5 sec lag between physical button trigger and actual switch response;

### ISSUE THREAD

**Issue by Dionice** [hongtat/tasmota-connect#24]
**Preconditions:** 
- Samsung SmartThings Hub v3; v000.036.00005;
- Sonoff mini - Tasmota 9.3.1;
- App: Tasmota Connect 1.1.2;

**Steps to reproduce:**
1) Connect Sonoff mini to Smartthings hub using Tasmota Connect app;
2) Make ST hub offline;
3) Trigger physical switch of Sonoff mini few times with less than 4 sec between clicks;

**Expected result:** No lag when using physical switch when ST hub is offline;
**Actual result:** 5 sec lag between physical button trigger and actual switch responce;

**Log:** 
16:57:01.575 RSL: RESULT = {"Rule2":"ON","Once":"OFF","StopOnError":"OFF","Length":383,"Free":128,"Rules":"ON Power5#state DO WebSend [192.168.0.10:39500] /?json={\"StatusSTS\":{\"POWER5\":\"%value%\"}} ENDON ON Power6#state DO WebSend [192.168.0.10:39500] /?json={\"StatusSTS\":{\"POWER6\":\"%value%\"}} ENDON ON Power7#state DO WebSend [192.168.0.10:39500] /?json={\"StatusSTS\":{\"POWER7\":\"%value%\"}} ENDON ON Power8#state DO WebSend [192.168.0.10:39500] /?json={\"StatusSTS\":{\"POWER8\":\"%value%\"}} ENDON"}
16:57:01.730 RSL: STATUS11 = {"StatusSTS":{"Time":"2021-04-11T16:57:01","Uptime":"0T00:34:49","UptimeSec":2089,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":21,"MqttCount":0,"POWER":"ON","Wifi":{"AP":1,"SSId":"Zhu","BSSId":"52:FF:20:57:11:D1","Channel":8,"RSSI":100,"Signal":-41,"LinkCount":1,"Downtime":"0T00:00:03"}}}
16:57:08.067 RSL: RESULT = {"POWER":"OFF"}
16:57:08.070 RSL: POWER = OFF
16:57:08.100 RUL: POWER1#STATE performs "WebSend [192.168.0.10:39500] /?json={"StatusSTS":{"POWER1":"0"}}"
16:57:08.437 RSL: RESULT = {"WebSend":"Done"}
16:57:20.425 RSL: STATE = {"Time":"2021-04-11T16:57:20","Uptime":"0T00:35:08","UptimeSec":2108,"Heap":27,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":0,"POWER":"OFF","Wifi":{"AP":1,"SSId":"Zhu","BSSId":"52:FF:20:57:11:D1","Channel":8,"RSSI":100,"Signal":-39,"LinkCount":1,"Downtime":"0T00:00:03"}}
16:57:20.435 RSL: SENSOR = {"Time":"2021-04-11T16:57:20","Switch1":"ON"}
16:59:11.841 RSL: RESULT = {"POWER":"ON"}
16:59:11.844 RSL: POWER = ON
16:59:11.860 RUL: POWER1#STATE performs "WebSend [192.168.0.10:39500] /?json={"StatusSTS":{"POWER1":"1"}}"
16:59:16.912 RSL: RESULT = {"WebSend":"Connect failed"}
16:59:16.999 RSL: RESULT = {"POWER":"OFF"}
16:59:16.001 RSL: POWER = OFF
16:59:17.014 RUL: POWER1#STATE performs "WebSend [192.168.0.10:39500] /?json={"StatusSTS":{"POWER1":"0"}}"
16:59:22.035 RSL: RESULT = {"WebSend":"Connect failed"}
16:59:40.485 RSL: RESULT = {"POWER":"ON"}
16:59:40.488 RSL: POWER = ON
16:59:40.504 RUL: POWER1#STATE performs "WebSend [192.168.0.10:39500] /?json={"StatusSTS":{"POWER1":"1"}}"
16:59:45.587 RSL: RESULT = {"WebSend":"Connect failed"}
16:59:47.017 RSL: RESULT = {"POWER":"OFF"}
16:59:47.020 RSL: POWER = OFF
16:59:47.036 RUL: POWER1#STATE performs "WebSend [192.168.0.10:39500] /?json={"StatusSTS":{"POWER1":"0"}}"
16:59:52.264 RSL: RESULT = {"WebSend":"Connect failed"}
17:02:16.963 RSL: RESULT = {"POWER":"ON"}
17:02:16.966 RSL: POWER = ON
17:02:16.986 RUL: POWER1#STATE performs "WebSend [192.168.0.10:39500] /?json={"StatusSTS":{"POWER1":"1"}}"
17:02:22.055 RSL: RESULT = {"WebSend":"Connect failed"}
17:02:22.435 RSL: RESULT = {"POWER":"OFF"}
17:02:22.438 RSL: POWER = OFF

**Comment by hongtat** [comment]
It will not work when the hub is offline.
