### ISSUE TITLE
Tasmota connect v 1.1.1 - Smartthings - IP Address

### ISSUE THREAD

**Issue by pnsiva** [hongtat/tasmota-connect#27]
Is it possible to include a feature to type host name or IP Address on your next version of Tasmota connect? When there is an IP change/ network change on my router I need to manually update the Tasmota connect IP addresses using Smartthings App.  When you have 30 Tasmota devices it is a pain to update them all manually. If IP address/ Hostname is implemented. My router will resolve the hostname (device name) to IP address and I don't need to update them manually. Thanks for your consideration.

**Comment by hongtat** [comment]
It is not possible, because Smartthings doesn't support it. Static IP address is a requirement.
