### ISSUE TITLE
Cannot uninstall SmartApp Tasmota(Connect)

### ISSUE THREAD

**Issue by castlestone** [hongtat/tasmota-connect#3]
My installation of Tasmota(Connect) does not seem to be working.  I cannot add a second device.
First thought was to update from repo but when I open the Update from Repo there are 2 instances of "tasmota-connect (master)".
That didn't look right so I tried to uninstall the App:  My Locations -> SmartApps -> Edit -> Uninstall
That did nothing.
I did a right click on the Uninstall button and copied the link address.  When I put that in the browser I got:  HTTP Status 405  The specified HTTP method is not allowed for the requested resource.

Any suggestions

**Comment by hongtat** [comment]
You have to use the SmartThings mobile app to install new Tasmota device.

To uninstall the SmartApp, you have to use the mobile app too.

**Comment by castlestone** [comment]
Thanks for the quick reply.
I tried that but the attached screenshot shows what I got:




![Screenshot_20200421-065948_SmartThings](https://user-images.githubusercontent.com/6169654/79854836-750cca80-83a0-11ea-8b73-9cc6dd5b2e51.jpg)

**Comment by hongtat** [comment]
I'm not familiar with that screenshot. How do you get to that?

If you follow the instruction, you should get similar to [this](https://community.smartthings.com/t/release-tasmota-connect-pure-tasmota-st-integration-real-time-status-for-sonoff-tuya-smartlife-other-esp8266-devices/187553).

**Comment by castlestone** [comment]
I opened smartthings classic, selected "automation", then selected "SmartApps" , then selected "Tasmota(Connect)" , scrolled to the bottom and clicked on "Remove" and the image above is what comes up.

I also tried the new SmartThings app.  I cannot even open "Tasmota(Connect)"  I get an error message:  " A network or server error occured.  Try again later"  I have no problem opening other SmartApps.

Is there any way to force uninstall in the IDE?

**Comment by castlestone** [comment]
OK I managed to delete it.
The first thing I did was to delete all the related device drivers and to do that I had to delete all the devices that were using the drivers.
Then when I went into the Smarthings Classic App, I was able to delete Tasmota(Connect)

Now to reinstall everything!
