### ISSUE TITLE
Sonoff pow2 reports NULL in powermeter although tasmota gets it right.

### ISSUE THREAD

**Issue by blurkis** [hongtat/tasmota-connect#4]
I flashed a sonoff pow2 with recent tasmota. It workes great. I then added your devicehandlers and smartapp.  The switch works, I can turn it off/on.  The problem is that many times it reports NULL in powermeter.   I have uploaded pictures here: https://community.smartthings.com/t/release-tasmota-connect-for-sonoff-tuya-smartlife-other-esp8266-devices/187553

Search for Kent_Nyberg.  As seen, everything seems to be installed correct. So Im having trouble finding out why it reports NULL.

**Comment by hongtat** [comment]
Fixed.
