### ISSUE TITLE
Power meter parameters can`t be used in automation.

### ISSUE THREAD

**Issue by Jhonattan-Souza** [hongtat/tasmota-connect#5]
Hi ! Thanks for the great job you`ve done in this application.

Do you know how can I use power meter parameters, voltage, amperage etc, in my automations ? Only the on off option are able to use as conditions in my app.

Best regards, and thanks again!

**Comment by hongtat** [comment]
The official automation is rather limited.
Consider using WebCore if you require complex automation.

https://community.smartthings.com/c/smartapps/webCoRE/83
