### ISSUE TITLE
Problem connecting tasmota with smartthings

### ISSUE THREAD

**Issue by abdallahmhs** [hongtat/tasmota-connect#7]
![Screenshot_2020-06-03-14-50-50-08](https://user-images.githubusercontent.com/66330572/83794196-f0e77b80-a69d-11ea-9440-fa36861c501e.jpg)
![Screenshot_2020-06-03-14-50-59-20](https://user-images.githubusercontent.com/66330572/83794218-f775f300-a69d-11ea-91e3-b89aff9c0dd6.jpg)

smartthings don't work with me on version 8.3.1 version 8.2.0 and version 8.1.0 I don't know what my problem is and how it can be solved

**Comment by hongtat** [comment]
What are you trying to do?

**Comment by abdallahmhs** [comment]
I want to control tasmota via smartthings

**Comment by hongtat** [comment]
What have you tried and what is not working?

**Comment by abdallahmhs** [comment]
Does it require adding something on raw tasmota to work with on smartthings?

**Comment by hongtat** [comment]
Can you please update your codes and try again?
If it doesn't work, can you please provide more details? What device are you adding?
