### ISSUE TITLE
App Does not switch "Tasmota Generic Switch" with Tasmota 8.3.1

### ISSUE THREAD

**Issue by BlueFinBima** [hongtat/tasmota-connect#8]
Hello Tan,  

Opening a new issue because this may or may not be the same as #7.
I installed Tasmota-Connect today from **master**.

Tasmota Program Version | **8.3.1(tasmota)** on a **Sonoff Mini**

I have defined the device handler as 

> "Tasmota Generic Switch"

On both Classic and New apps, I cannot control On/Off for the device.  Both Apps correctly reflect toggling On/Off in the Web Admin for the device, and I see from the console, that these state changes are being websent to SmartThings Hub (which I presume is the reason the state shows in the Apps) but I see no sign of anything in the console for the device when I press the ON/OFF button in the App.

When I press the App button (in this case "On") I see this event in the SmartThings log, however the device state does not change.
![image](https://user-images.githubusercontent.com/18526232/83901508-c86d8900-a752-11ea-83c7-8464b38fab59.png)

The device in the App is defined with both a userid "admin" and the password is the "Web Admin Password" defined in the "Other Parameters" configuration page for the device.

This is my first Tasmota device on SmartThings so highly possible that I have messed something up.

Many thanks for creating Tasmota-Connect, and I would appreciate your considered opinion on the symptoms I am seeing.

Regards

**Comment by hongtat** [comment]
Hi,

Can you clear the password? Don't use password. It could be the password issue.

**Comment by BlueFinBima** [comment]
Hi Tan,  thanks for responding so quickly.   I set "WebPassword 0" and then cleared the password and userid in the device.  The result was that the Sonoff Mini is controllable now.  While the Tasmota security is not very secure because passwords flow in the clear, I would still like to use a password.
Having examined the code, it might be helpful to know that the following special characters appear in the password I am using "%],_^['!=". 
Regards,  Neil

**Comment by BlueFinBima** [comment]
Pull request #9 created for this problem.
